AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LoftwahRailsLambda

Parameters:

  RailsEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - production

Globals:

  Function:
    Environment:
      Variables:
        RAILS_ENV: !Ref RailsEnv

Resources:

  RailsLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
      DockerTag: web
      DockerBuildArgs:
        RAILS_ENV: !Ref RailsEnv
    Properties:
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        HttpApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref RailsHttpApi
      MemorySize: 1792
      PackageType: Image
      Timeout: 30

  RailsHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref RailsEnv

Outputs:

  LoftwahRailsLambdaHttpApiUrl:
    Description: Lambda Invoke URL
    Value: !Sub https://${RailsHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${RailsEnv}/

  LoftwahRailsLambdaLambdaResourceArn:
    Description: Lambda ARN
    Value: RailsLambda.Arn
